app:
  name: ffly-basic
  mode: production
  port: 60000
  jwt_secret: your-jwt-secret-key
  jwt_expire: 86400 # 24 hours

mysql:
  host: 192.168.111.132
  port: 3306
  user: root
  password: root
  database: ffly_basic
  max_idle_conns: 10
  max_open_conns: 100
  connection_max_lifetime: 60

redis:
  host: 192.168.111.132
  port: 6379
  password: "redis123" # 密码为空
  db: 0 # 默认数据库
  pool_size: 100 # 连接池大小
  min_idle_conns: 10 # 最小空闲连接数
